name: 'AMTool GitHub Actions'
description: 'Runs Alertmanager AMTool commands via GitHub Actions.'
author: 'Wei Wu'
inputs:
  amtool_check_file:
    description: 'Path to file that AMTool will perform check on. Default to alertmanager.yaml'
    default: 'alertmanager.yaml'
runs:
  using: 'docker'
  image: './Dockerfile'
